# Sử dụng hình ảnh chính thức của Eclipse Mosquitto
FROM eclipse-mosquitto:latest

# Sao chép tệp cấu hình vào container
COPY mosquitto.conf /mosquitto/config/mosquitto.conf

# Expose các cổng cần thiết
EXPOSE 1883 9001